### ISSUE TITLE
Build errors in 0.6.1

### ISSUE THREAD

**Issue by mdmintz** [chrieke/mkdocs-exclude-search#28]
Hi, I'm getting errors when building docs while using ``mkdocs_exclude_search==0.6.1``

Stack trace below:

```bash
...
Successfully installed mkdocs-exclude-search-0.6.1

$ mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory:
            /Users/michael/github/SeleniumBase/site
Traceback (most recent call last):
  File "/Users/michael/.virtualenvs/sbase9/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/mkdocs/commands/build.py", line 317, in build
    config['plugins'].run_event('post_build', config=config)
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/mkdocs/plugins.py", line 104, in run_event
    result = method(**kwargs)
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/mkdocs_exclude_search/plugin.py", line 258, in on_post_build
    included_records = self.select_included_records(
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/mkdocs_exclude_search/plugin.py", line 228, in select_included_records
    elif self.is_ignored_record(rec_file_name, rec_header_name, to_ignore):
  File "/Users/michael/.virtualenvs/sbase9/lib/python3.9/site-packages/mkdocs_exclude_search/plugin.py", line 148, in is_ignored_record
    (
TypeError: 'NoneType' object is not iterable
```

**Comment by chrieke** [comment]
@mdmintz Hi Michael, thanks for reporting! Could you post your plugin config, and maybe also test if it works with pip install mkdocs-exclude-search==0.5.4?

It seems the changes made after 0.6.0 still lead to issues, but even though I added a lot of tests it is really hard to take care of every possible config. Thanks!

**Comment by mdmintz** [comment]
Hi @chrieke, Everything was working with ``mkdocs-exclude-search==0.5.4``. Going from ``0.5.4`` to ``0.6.1`` broke the build.

Here's my pip list:

```
appdirs==1.4.4
appnope==0.1.2
async-generator==1.10
attrs==21.2.0
backcall==0.2.0
backports.entry-points-selectable==1.1.1
beautifulsoup4==4.10.0
bleach==4.1.0
boto==2.49.0
build==0.7.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.9
click==8.0.3
colorama==0.4.4
commonmark==0.9.1
coverage==6.2
cryptography==36.0.1
csscompressor==0.9.5
cssselect==1.1.0
decorator==5.1.0
distlib==0.3.4
docutils==0.18.1
execnet==1.9.0
fasteners==0.16.3
filelock==3.4.0
flake8==4.0.1
future==0.18.2
ghp-import==2.0.2
h11==0.12.0
htmlmin==0.1.12
idna==3.3
importlib-metadata==4.10.0
iniconfig==1.1.1
ipdb==0.13.9
ipython==7.30.1
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.0.3
joblib==1.1.0
jsmin==3.0.0
keyring==23.4.0
livereload==2.6.3
lunr==0.6.1
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mergedeep==1.3.4
mkdocs==1.2.3
mkdocs-exclude-search==0.6.1
mkdocs-material==8.1.3
mkdocs-material-extensions==1.0.3
mkdocs-minify-plugin==0.5.0
mkdocs-simple-hooks==0.1.4
monotonic==1.6
more-itertools==8.12.0
nltk==3.6.6
nose==1.3.7
outcome==1.1.0
packaging==21.3
parameterized==0.8.1
parso==0.8.3
pdfminer.six==20211012
pep517==0.12.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
pkginfo==1.8.2
platformdirs==2.4.0
pluggy==1.0.0
prompt-toolkit==3.0.24
ptyprocess==0.7.0
py==1.11.0
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
Pygments==2.10.0
pymdown-extensions==9.1
PyMySQL==1.0.2
pyOpenSSL==21.0.0
pyotp==2.6.0
pyparsing==3.0.6
pytest==6.2.5
pytest-cov==3.0.0
pytest-forked==1.4.0
pytest-html==2.0.1
pytest-metadata==1.11.0
pytest-ordering==0.6
pytest-rerunfailures==10.2
pytest-xdist==2.5.0
python-dateutil==2.8.2
PyYAML==6.0
pyyaml_env_tag==0.1
readme-renderer==32.0
regex==2021.11.10
requests==2.26.0
requests-toolbelt==0.9.1
rfc3986==1.5.0
rich==10.16.1
sbvirtualdisplay==1.0.0
selenium==4.1.0
seleniumbase==2.3.1
setuptools-scm==6.3.2
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.3.1
stevedore==3.5.0
toml==0.10.2
tomli==2.0.0
tornado==6.1
tqdm==4.62.3
traitlets==5.1.1
trio==0.19.0
trio-websocket==0.9.2
twine==3.7.1
urllib3==1.26.7
virtualenv==20.10.0
virtualenv-clone==0.5.7
virtualenvwrapper==4.8.4
watchdog==2.1.6
wcwidth==0.2.5
webencodings==0.5.1
wsproto==1.0.0
zipp==3.6.0
```

**Comment by mdmintz** [comment]
@chrieke, And if it helps, here's the mkdocs.yml file that was used: https://github.com/seleniumbase/SeleniumBase/blob/master/mkdocs.yml

**Comment by chrieke** [comment]
Thanks, that was super helpful! Fixed in https://github.com/chrieke/mkdocs-exclude-search/pull/29 & version 0.6.2. Sorry for the incenviance, maybe over the holidays I will be able to add more end-to-end test cases, the 0.6.0 release was maybe a bit rushed. Let me know if there are any other issues.
