### ISSUE TITLE
Build error in 0.6.2 when "nav:" is not used

### ISSUE THREAD

**Issue by hbokh** [chrieke/mkdocs-exclude-search#30]
With version 0.6.2 I get the errors below when running `mkdocs build`.
Because I do not use any "navigation section" aka `nav:` in file `mkdocs.yml`, this might be my issue here.

Reverting to 0.5.4 does work.

```console
❯ mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /Users/hbokh/Projects/Spindle/infra/infra-docs/site
Traceback (most recent call last):
  File "/Users/hbokh/.virtualenvs/mkdocs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/mkdocs/commands/build.py", line 317, in build
    config['plugins'].run_event('post_build', config=config)
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/mkdocs/plugins.py", line 104, in run_event
    result = method(**kwargs)
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/mkdocs_exclude_search/plugin.py", line 258, in on_post_build
    navigation_items = explode_navigation(navigation=config.data["nav"])
  File "/Users/hbokh/.virtualenvs/mkdocs/lib/python3.9/site-packages/mkdocs_exclude_search/utils.py", line 27, in explode_navigation
    for chapter in navigation:
TypeError: 'NoneType' object is not iterable
```

**Comment by chrieke** [comment]
Thanks! Fixed in new release 0.6.3 on pypi. Also extended the tests and added a pipeline to test on various "used by" repositories before new release. Hoping this finally makes the last feature release stable :) Thanks again for the reports, happy holidays!
