### ISSUE TITLE
Build error after upgrade to mkdocs-exclude-search 0.6.0-0.6.3

### ISSUE THREAD

**Issue by johnthagen** [chrieke/mkdocs-exclude-search#35]
After updating `mkdocs-exclude-search` from `0.5.3` to `0.6.3` I get the following build error:

```
mkdocs build
INFO     -  [macros] - Macros arguments: {'module_name': 'main', 'modules': [], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'verbose': False}
INFO     -  [macros] - Extra variables (config file): ['social', 'generator', 'version']
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: site
Traceback (most recent call last):
  File ".tox/docs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File ".tox/docs/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File ".tox/docs/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File ".tox/docs/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".tox/docs/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".tox/docs/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File ".tox/docs/lib/python3.9/site-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File ".tox/docs/lib/python3.9/site-packages/mkdocs/commands/build.py", line 317, in build
    config['plugins'].run_event('post_build', config=config)
  File ".tox/docs/lib/python3.9/site-packages/mkdocs/plugins.py", line 104, in run_event
    result = method(**kwargs)
  File ".tox/docs/lib/python3.9/site-packages/mkdocs_exclude_search/plugin.py", line 278, in on_post_build
    navigation_items = explode_navigation(navigation=nav)
  File ".tox/docs/lib/python3.9/site-packages/mkdocs_exclude_search/utils.py", line 31, in explode_navigation
    chapter_paths = list(chapter.values())[0]
AttributeError: 'str' object has no attribute 'values'
ERROR: InvocationError for command .tox/docs/bin/mkdocs build (exited with code 1)
```

Relevant configuration from `mkdocs.yml`:

```yaml
plugins:
  - search
  - macros
  - exclude-search:
      exclude:
        - licenses/*
 ```

### Environment

- Python 3.9.8

```shell
pip list
Package                    Version
-------------------------- ---------
beautifulsoup4             4.10.0
certifi                    2021.10.8
charset-normalizer         2.0.9
click                      8.0.3
distlib                    0.3.4
filelock                   3.4.2
ghp-import                 2.0.2
idna                       3.3
importlib-metadata         4.10.0
Jinja2                     3.0.3
lxml                       4.7.1
Markdown                   3.3.6
MarkupSafe                 2.0.1
mergedeep                  1.3.4
mkdocs                     1.2.3
mkdocs-exclude-search      0.6.3
mkdocs-htmlproofer-plugin  0.8.0
mkdocs-macros-plugin       0.6.3
mkdocs-material            8.1.4
mkdocs-material-extensions 1.0.3
packaging                  21.3
pep517                     0.12.0
pip                        21.3.1
pip-tools                  6.4.0
platformdirs               2.4.1
pluggy                     1.0.0
py                         1.11.0
Pygments                   2.11.1
pymdown-extensions         9.1
pyparsing                  3.0.6
python-dateutil            2.8.2
PyYAML                     6.0
pyyaml_env_tag             0.1
requests                   2.26.0
setuptools                 58.5.3
six                        1.16.0
soupsieve                  2.3.1
termcolor                  1.1.0
toml                       0.10.2
tomli                      1.2.2
tox                        3.24.5
urllib3                    1.26.7
virtualenv                 20.13.0
watchdog                   2.1.6
wheel                      0.37.1
zipp                       3.7.0
```

**Comment by johnthagen** [comment]
I bisected this to the 0.6.0 release as the first release where this build error happens. 0.5.4 release works as expected.

**Comment by prescod** [comment]
I have also seen this error. chapter_paths is the value "index.md" in my case.

**Comment by chrieke** [comment]
Hi @johnthagen @prescod thanks for reporting! This seems to be when in the nav section a chapter is provided without chapter name, [here](https://www.mkdocs.org/user-guide/configuration/#documentation-layout). I wasn't aware of this option, will fix & add test asap.

**Comment by chrieke** [comment]
Fixed with https://github.com/chrieke/mkdocs-exclude-search/pull/36 in new version 0.6.4, please update via `pip install mkdocs-exclude-search --upgrade`.

**Comment by johnthagen** [comment]
Thanks @chrieke for the great plugin!

**Comment by johnthagen** [comment]
@chrieke I wanted to report that I tested 0.6.4 on our production application and everything is building/working as expected again. Thanks!
