### ISSUE TITLE
Recursive include directory?

### ISSUE THREAD

**Issue by kratsg** [chrieke/mkdocs-exclude-search#4]
It would be nice if we could include entire directories (that contain other directories). This could be done by using `fnmatch` to do the pattern matching instead so something like `exclude: directory/` or `exclude: directory/*` works as expected -- rather than just the files in a particular directory.

**Comment by chrieke** [comment]
@kratsg Yeah the directory exclusion is not ideal, thanks for the suggestion. Will look into this for the next version.

**Comment by chrieke** [comment]
@kratsg The new [version 0.4.0](https://github.com/chrieke/mkdocs-exclude-search/releases/tag/0.4.0) adds this feature thanks to @seppi91 ! Please upgrade via `pip install mkdocs-exclude-search --upgrade`. See the readme for how to apply the directory exclusions.

Let me know if you encounter any problems!

**Comment by Stanzilla** [comment]
Looks like that broke my deploy:

```
10:16:30 AM: Traceback (most recent call last):
10:16:30 AM:   File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in <module>
10:16:30 AM:     sys.exit(cli())
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
10:16:30 AM:     return self.main(*args, **kwargs)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
10:16:30 AM:     rv = self.invoke(ctx)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
10:16:30 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
10:16:30 AM:     return ctx.invoke(self.callback, **ctx.params)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
10:16:30 AM:     return callback(*args, **kwargs)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 152, in build_command
10:16:30 AM:     build.build(config.load_config(**kwargs), dirty=not clean)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 295, in build
10:16:30 AM:     config['plugins'].run_event('post_build', config=config)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/plugins.py", line 96, in run_event
10:16:30 AM:     result = method(**kwargs)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_exclude_search/plugin.py", line 211, in on_post_build
10:16:30 AM:     to_exclude = self.resolve_excluded_records(to_exclude=to_exclude)
10:16:30 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_exclude_search/plugin.py", line 77, in resolve_excluded_records
10:16:30 AM:     excluded_entries[idx] = file_name, header_name
10:16:30 AM: TypeError: 'str' object does not support item assignment
```

**Comment by seppi91** [comment]
Hi @Stanzilla 
Your exclude config should bei a list, youve defined a string

**Comment by Stanzilla** [comment]
@seppi91 thanks! Still a breaking change, should probably be in the release notes

**Comment by kratsg** [comment]
> Let me know if you encounter any problems!

Worked very nicely out of the box :) Thanks! (Sorry for what seemed like a drive-by issue at the time)

**Comment by chrieke** [comment]
Perfect, thanks all for your help! Closing then.

@Stanzilla Added a note in the release note, thanks.
