### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by jparthasarthy** [chrieke/mkdocs-exclude-search#7]
Incredibly useful Python package by the way. Solved my exact problem.

Getting this error when running the example in the readme.md:

```
[I 210302 14:09:09 watcher:104] Running task: builder (delay: None)
INFO    -  Running task: builder (delay: None)
INFO    -  Building documentation... 
ERROR   -  Config value: 'plugins'. Error: Invalid Plugins configuration 
[E 210302 14:09:09 ioloop:909] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.7/site-packages/livereload/handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/local/lib/python3.7/site-packages/livereload/watcher.py", line 105, in examine
        func()
      File "/usr/local/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 129, in builder
        **kwargs
      File "/usr/local/lib/python3.7/site-packages/mkdocs/config/base.py", line 210, in load_config
        "Aborted with {} Configuration Errors!".format(len(errors))
    mkdocs.exceptions.ConfigurationError: Aborted with 1 Configuration Errors!
ERROR   -  Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/usr/local/lib/python3.7/site-packages/livereload/handlers.py", line 69, in poll_tasks
    filepath, delay = cls.watcher.examine()
  File "/usr/local/lib/python3.7/site-packages/livereload/watcher.py", line 105, in examine
    func()
  File "/usr/local/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 129, in builder
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/mkdocs/config/base.py", line 210, in load_config
    "Aborted with {} Configuration Errors!".format(len(errors))
mkdocs.exceptions.ConfigurationError: Aborted with 1 Configuration Errors!
```

I'll try using a previous version. This is version 4.0.0.

**Comment by chrieke** [comment]
Thanks @jparthasarthy for the kind word and report. Could you post your full mkdocs plugin configuration here? From the error message I'm not able to see what might be wrong. Using the example configuration from the readme works for me, obviously the files don't exist.

**Comment by jparthasarthy** [comment]
Sure. Here's my fill config:

```
site_name: <>
docs_dir: "docs"
site_dir: "site"
theme:
  name: "material"
  favicon: "assets/favicon.png"
  language: "en"
  palette:
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: assets/logo.png
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - exclude-search:
    - exclude:
      - <>filepath/*.md
use_directory_urls: false
strict: true
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/asciinema-player@2.6.1/resources/public/css/asciinema-player.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/asciinema-player@2.6.1/resources/public/js/asciinema-player.min.js
```

**Comment by chrieke** [comment]
Thanks! Are you trying to exclude one specific .md file or all .md files in a directory? Should either be:

For a file:
```
- exclude:
   - filepath.md
```

Or for a directory:
```
- exclude:
   - dirpath/*.md
```
I'm assuming <> is a placeholder etc?

**Comment by chrieke** [comment]
Closing, hope the above solved your problem. Please feel free to reopen and let me know if you still encounter any issues!
